### PR TITLE
Use property attributes if not present in documentation attribute

### PR DESCRIPTION
**Pull request by Kris-LIBIS**
The type and values are often already defined on the property (e.g. when using Representable::Coercion). It's not useful to always have to repeat the info in a separate 'documentation' Hash.

This patch will get the type, desc and values settings from the property if there is no such thing in the documentation Hash. The spec was slightly modified to test the new functionality.

### CODE REVIEW

**Comment by Kris-LIBIS** [comment]
All checks fail except for Ruby 2.3. It is not during testing, though but during bundle install. Apparently the most recent Rack gem is no longer compatible with older rubies:

'Gem::InstallError: rack requires Ruby version >= 2.2.2.'

On jruby 1.9 mode the tool gem is also complaining and rbx-2 doesn't even install.

On the other hand, the allowed failures ruby-head and jruby-head are running fine.

**Comment by Kris-LIBIS** [comment]
I tried to force rack on version 1.6, but that did not work:

    Bundler could not find compatible versions for gem "ruby":
      In Gemfile:
        ruby
    
        grape-swagger was resolved to 0.26.1, which depends on
          ruby (>= 2.2.6)

Probably best to drop support for ruby < 2.3 and jruby < 9.0.0.0 ?

**Comment by kzaitsev** [comment]
Hello, thank you, looks good.

I updated `.travis.yml`, please rebase your branch

I don't want to drop ruby 2.2.x now.

**Comment by Kris-LIBIS** [comment]
2.2.6 is fine indeed. I merged and pushed to my fork. I haven't synced a fork with the original repository before. I hope it's OK like that. Otherwise let me know what to do.

**Comment by kzaitsev** [comment]
all ok, thank you

**Comment by kzaitsev** [comment]
0.1.4 released

**Comment by Kris-LIBIS** [comment]
Thanks!

**Pull request merged**
